[tool.poetry]
name = "entitlements"
version = "0.1.0"
description = ""
authors = ["nub <dev@nubco.xyz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
lief = "^0.13.0"
openai = "^0.27.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
